// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kit "github.com/uala-challenge/tweets-service/kit"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, rqt
func (_m *Service) Apply(ctx context.Context, rqt kit.TweetRequest) (string, error) {
	ret := _m.Called(ctx, rqt)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, kit.TweetRequest) (string, error)); ok {
		return rf(ctx, rqt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, kit.TweetRequest) string); ok {
		r0 = rf(ctx, rqt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, kit.TweetRequest) error); ok {
		r1 = rf(ctx, rqt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
